language: go
go:
  - "1.10"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgl1-mesa-dev xorg-dev
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
